import {
  IPC_CHANNEL_KEY_PRESSED_DOWN,
  IPC_CHANNEL_KEY_PRESSED_LEFT,
  IPC_CHANNEL_KEY_PRESSED_RIGHT,
  IPC_CHANNEL_KEY_PRESSED_SPACE,
  IPC_CHANNEL_KEY_PRESSED_UP
} from '../constants/main/ipc';

const GlobalShortcutChannel = {
  UP: IPC_CHANNEL_KEY_PRESSED_UP,
  DOWN: IPC_CHANNEL_KEY_PRESSED_DOWN,
  LEFT: IPC_CHANNEL_KEY_PRESSED_LEFT,
  RIGHT: IPC_CHANNEL_KEY_PRESSED_RIGHT,
  SPACE: IPC_CHANNEL_KEY_PRESSED_SPACE,
} as const;

export type GlobalShortcutChannel = (typeof GlobalShortcutChannel)[keyof typeof GlobalShortcutChannel];
